/* NUS Restricted */

/* ----------------------------------------------------------------------
TABLE: PRSCTABLE
---------------------------------------------------------------------- */
CREATE TABLE PRSDBM.PRSCTABLE
(
	CODE_C 	  VARCHAR2 (50) NOT NULL ,
	CODE_T 	  VARCHAR2 (100) NOT NULL,
	DEFUNCT_F VARCHAR2 (1) NOT NULL
)
;--TABLESPACE S1_DAT;

COMMENT ON TABLE PRSDBM.PRSCTABLE IS 'This exclusive code table stores the list of common defined codes that are used in the Purchase Requisition System.' ;
COMMENT ON COLUMN PRSDBM.PRSCTABLE.CODE_C IS 'Commonly defined code.' ;
COMMENT ON COLUMN PRSDBM.PRSCTABLE.CODE_T IS 'Code Description.' ;
COMMENT ON COLUMN PRSDBM.PRSCTABLE.DEFUNCT_F IS 'Flag to denote if code is no longer in use (Y, N).' ;

/* ----------------------------------------------------------------------
CONSTRAINT:  Format is SYSTEM_TABLE_KEY_COL(S)
KEY Type: PK (Primary Key), FK (Foreign Key), UK (Unique Key), CK (Constraint), I (INDEX)
---------------------------------------------------------------------- */

ALTER TABLE PRSDBM.PRSCTABLE ADD (
CONSTRAINT PRS_PCT_PK_CC
PRIMARY KEY (CODE_C)
	--USING INDEX
	--TABLESPACE S1_IDX
);

ALTER TABLE PRSDBM.PRSCTABLE ADD (
CONSTRAINT PRS_PCT_CK_DF
CHECK (DEFUNCT_F IN ('Y', 'N')));
/* ----------------------------------------------------------------------
GRANT: Who and what privilege to grant
---------------------------------------------------------------------- */
GRANT DELETE, INSERT, SELECT, UPDATE ON PRSDBM.PRSCTABLE TO PRJPRS;

GRANT SELECT ON PRSDBM.PRSCTABLE TO RPTPRS;


/* ----------------------------------------------------------------------
2. TABLE: PRS_TRAN_LOG
---------------------------------------------------------------------- */
CREATE TABLE PRSDBM.PRS_TRAN_LOG
(
	LOG_TRAN_N VARCHAR2(11) NOT NULL,
	TRAN_TP_C VARCHAR2(50),
	TRAN_DTM DATE NOT NULL,
	PROG_FUNC_C VARCHAR2(50) NOT NULL,
	USER_I VARCHAR2(12) NOT NULL,
	USER_IPADDR_T VARCHAR2(15) NOT NULL,
	TRAN_BF_T CLOB,
	TRAN_AF_T CLOB
)
;--TABLESPACE S1_DAT;

COMMENT ON TABLE PRSDBM.PRS_TRAN_LOG IS 'Transaction log table for the Purchase Requisition System.';
COMMENT ON COLUMN PRSDBM.PRS_TRAN_LOG.LOG_TRAN_N IS 'ID for the transaction log record. Generated by Oracle sequence.';
COMMENT ON COLUMN PRSDBM.PRS_TRAN_LOG.TRAN_TP_C IS 'Transaction type code for this transaction. E.g. Insert, Update, Delete. Nullable as Login and Logout updates no data.';
COMMENT ON COLUMN PRSDBM.PRS_TRAN_LOG.TRAN_DTM IS 'Date and time of transaction.';
COMMENT ON COLUMN PRSDBM.PRS_TRAN_LOG.PROG_FUNC_C IS 'Program function that the transaction applies to. E.g. Insert,Update, etc.';
COMMENT ON COLUMN PRSDBM.PRS_TRAN_LOG.USER_I IS 'User ID performing the transaction. Staff number/ Student number.Validated by application.';
COMMENT ON COLUMN PRSDBM.PRS_TRAN_LOG.USER_IPADDR_T IS 'Machine IP address the request originates from.';
COMMENT ON COLUMN PRSDBM.PRS_TRAN_LOG.TRAN_BF_T IS 'Before image of data involved in the transaction in the form of JSON. Nullable as transactions such as log in and log out have no data to save.';
COMMENT ON COLUMN PRSDBM.PRS_TRAN_LOG.TRAN_AF_T IS 'After image of data involved in the transaction in the form of JSON. Nullable as transactions such as log in and log out have no data to save.';

/* ----------------------------------------------------------------------
CONSTRAINT:  Format is SYSTEM_TABLE_KEY_COL(S)
KEY Type: PK (Primary Key), FK (Foreign Key), UK (Unique Key), CK (Constraint), I (INDEX)
---------------------------------------------------------------------- */

ALTER TABLE PRSDBM.PRS_TRAN_LOG ADD (
CONSTRAINT PRS_PTL_PK_LTN
PRIMARY KEY (LOG_TRAN_N)
	--USING INDEX
	--TABLESPACE S1_IDX
);

ALTER TABLE PRSDBM.PRS_TRAN_LOG ADD (
CONSTRAINT PRS_PTL_FK_TTC
FOREIGN KEY (TRAN_TP_C)
REFERENCES PRSDBM.PRSCTABLE(CODE_C)
);

ALTER TABLE PRSDBM.PRS_TRAN_LOG ADD (
CONSTRAINT PRS_PTL_FK_PFC
FOREIGN KEY (PROG_FUNC_C)
REFERENCES PRSDBM.PRSCTABLE(CODE_C)
);

/* ----------------------------------------------------------------------
SEQUENCE: PRS_TRAN_LOG
---------------------------------------------------------------------- */
CREATE SEQUENCE PRSDBM.PRS_TRAN_LOG_SEQ
    START WITH 1
    MINVALUE 1
    INCREMENT BY 1
    NOCYCLE
    NOCACHE;

GRANT SELECT ON PRSDBM.PRS_TRAN_LOG_SEQ TO PRJPRS;

GRANT SELECT ON PRSDBM.PRS_TRAN_LOG_SEQ TO RPTPRS;

/* ----------------------------------------------------------------------
GRANT: Who and what privilege to grant
---------------------------------------------------------------------- */
GRANT DELETE, INSERT, SELECT, UPDATE ON PRSDBM.PRS_TRAN_LOG TO PRJPRS;

GRANT SELECT ON PRSDBM.PRS_TRAN_LOG TO RPTPRS;

/* ----------------------------------------------------------------------
TABLE: PRS_INTGR_STATUS
---------------------------------------------------------------------- */
CREATE TABLE PRSDBM.PRS_INTGR_STATUS
(
	INTGR_TRAN_N VARCHAR2(11) NOT NULL,
	CHNL_C VARCHAR2(20) NOT NULL,
	WS_URL_T VARCHAR2(500) NOT NULL,
	HOST_SERVER_T VARCHAR2(20) NOT NULL,
	HTTP_STS_C VARCHAR2(3) NOT NULL,
	INTGR_DUR_N NUMBER (20) NOT NULL,
	REQ_PAYLOAD CLOB,
	RESP_PAYLOAD CLOB,
	INTGR_TRAN_DTM DATE NOT NULL
)
;--TABLESPACE S1_DAT;

COMMENT ON TABLE PRSDBM.PRS_INTGR_STATUS IS 'Table stores Integration status of the inbound/outbound webservice calls for the Purchase Requisition System.';
COMMENT ON COLUMN PRSDBM.PRS_INTGR_STATUS.INTGR_TRAN_N IS 'Transaction Number for Integration status record. Generated by Oracle sequence.';
COMMENT ON COLUMN PRSDBM.PRS_INTGR_STATUS.CHNL_C IS 'Channel to be Inbound/Outbound.';
COMMENT ON COLUMN PRSDBM.PRS_INTGR_STATUS.WS_URL_T IS ' End point url of the webservice. ';
COMMENT ON COLUMN PRSDBM.PRS_INTGR_STATUS.HOST_SERVER_T IS 'Host name of Server.';
COMMENT ON COLUMN PRSDBM.PRS_INTGR_STATUS.HTTP_STS_C IS 'Http Status Code';
COMMENT ON COLUMN PRSDBM.PRS_INTGR_STATUS.INTGR_DUR_N IS 'webservice request / response in milliseconds.';
COMMENT ON COLUMN PRSDBM.PRS_INTGR_STATUS.REQ_PAYLOAD IS 'Request Payload';
COMMENT ON COLUMN PRSDBM.PRS_INTGR_STATUS.RESP_PAYLOAD IS 'Response Payload';
COMMENT ON COLUMN PRSDBM.PRS_INTGR_STATUS.INTGR_TRAN_DTM IS 'Date and time of the webservice request/response made.';

/* -----------------------
CONSTRAINT:  Format is SYSTEM_TABLE_KEY_COL(S)
KEY Type: PK (Primary Key), FK (Foreign Key), UK (Unique Key), CK (Constraint), I (INDEX)
---------------------------------------------------------------------- */

ALTER TABLE PRSDBM.PRS_INTGR_STATUS ADD (
CONSTRAINT PRS_PIS_PK_TN
PRIMARY KEY (INTGR_TRAN_N)
	--USING INDEX
	--TABLESPACE S1_IDX
);

-- ALTER TABLE PRSDBM.PRS_INTGR_STATUS ADD (
-- CONSTRAINT PRS_PIS_FK_ISC
-- FOREIGN KEY (INTGR_STS_C)
-- REFERENCES PRSDBM.PRSCTABLE(CODE_C)
-- );

ALTER TABLE PRSDBM.PRS_INTGR_STATUS ADD (
CONSTRAINT PRS_PIS_FK_ISC
FOREIGN KEY (CHNL_C)
REFERENCES PRSDBM.PRSCTABLE(CODE_C)
);


/* ----------------------------------------------------------------------
SEQUENCE: PRS_INTGR_STS_SEQ
---------------------------------------------------------------------- */
CREATE SEQUENCE PRSDBM.PRS_INTGR_STS_SEQ
    START WITH 1
    MINVALUE 1
    INCREMENT BY 1
    NOCYCLE
    NOCACHE;

GRANT DELETE, INSERT, SELECT, UPDATE ON PRSDBM.PRS_INTGR_STATUS TO PRJPRS;
/* ----------------------------------------------------------------------
GRANT: Who and what privilege to grant
---------------------------------------------------------------------- */
GRANT SELECT ON PRSDBM.PRS_INTGR_STS_SEQ TO PRJPRS;
-- TODO: No RPTPRS user yet.
-- GRANT SELECT ON PRS_INTGR_STS_SEQ TO RPTPRS;


/* ----------------------------------------------------------------------
PRSCTABLE: Populate code table
---------------------------------------------------------------------- */
INSERT INTO PRSCTABLE (CODE_C, CODE_T, DEFUNCT_F) VALUES ('ROLE_NUS_ADMIN', 'NUS Administrator', 'N');
INSERT INTO PRSCTABLE (CODE_C, CODE_T, DEFUNCT_F) VALUES ('ROLE_FAC_ADMIN', 'Faculty Administrator', 'N');
INSERT INTO PRSCTABLE (CODE_C, CODE_T, DEFUNCT_F) VALUES ('ROLE_DEPT_ADMIN', 'Department Administrator', 'N');
INSERT INTO PRSCTABLE (CODE_C, CODE_T, DEFUNCT_F) VALUES ('ROLE_REGULATORY', 'Regulatory Officer', 'N');
INSERT INTO PRSCTABLE (CODE_C, CODE_T, DEFUNCT_F) VALUES ('ROLE_PROCUREMENT', 'Procurement Officer', 'N');
INSERT INTO PRSCTABLE (CODE_C, CODE_T, DEFUNCT_F) VALUES ('ROLE_QUOTATION_APPV_AUTH', 'Quotation Approving Authority', 'N');
INSERT INTO PRSCTABLE (CODE_C, CODE_T, DEFUNCT_F) VALUES ('ROLE_GOODS_RECEIPT', 'Goods Receipt Officer', 'N');
INSERT INTO PRSCTABLE (CODE_C, CODE_T, DEFUNCT_F) VALUES ('ROLE_PRINCIPAL_INVESTIGATOR', 'Principal Investigator', 'N');
INSERT INTO PRSCTABLE (CODE_C, CODE_T, DEFUNCT_F) VALUES ('ROLE_RESEARCHER', 'Researcher', 'N');
INSERT INTO PRSCTABLE (CODE_C, CODE_T, DEFUNCT_F) VALUES ('ROLE_LAB_ADMIN', 'Laboratory Administrator', 'N');
INSERT INTO PRSCTABLE (CODE_C, CODE_T, DEFUNCT_F) VALUES ('ROLE_HEAD_OF_DEPARTMENT', 'Head of Department', 'N');
INSERT INTO PRSCTABLE (CODE_C, CODE_T, DEFUNCT_F) VALUES ('ROLE_DEAN', 'Dean', 'N');

INSERT INTO PRSCTABLE (CODE_C, CODE_T, DEFUNCT_F) VALUES ('USER_ATTR_PRIMARY', 'Primary', 'N');
INSERT INTO PRSCTABLE (CODE_C, CODE_T, DEFUNCT_F) VALUES ('USER_ATTR_QAA_5K_TO_15K', 'EPV 5,001 to 15,000', 'N');
INSERT INTO PRSCTABLE (CODE_C, CODE_T, DEFUNCT_F) VALUES ('USER_ATTR_QAA_15K_TO_100K','EPV 15,001 to 100,000', 'N');

INSERT INTO PRSCTABLE (CODE_C, CODE_T, DEFUNCT_F) VALUES ('TRN_TP_INS', 'Insert', 'N');
INSERT INTO PRSCTABLE (CODE_C, CODE_T, DEFUNCT_F) VALUES ('TRN_TP_UPD', 'Update', 'N');
INSERT INTO PRSCTABLE (CODE_C, CODE_T, DEFUNCT_F) VALUES ('TRN_TP_DEL', 'Delete', 'N');

INSERT INTO PRSCTABLE (CODE_C, CODE_T, DEFUNCT_F) VALUES ('PROG_FN_LOGIN', 'User Login', 'N');
INSERT INTO PRSCTABLE (CODE_C, CODE_T, DEFUNCT_F) VALUES ('PROG_FN_LOGOUT', 'User Logout', 'N');
INSERT INTO PRSCTABLE (CODE_C, CODE_T, DEFUNCT_F) VALUES ('PROG_FN_USERACCESS', 'User Access', 'N');
INSERT INTO PRSCTABLE (CODE_C, CODE_T, DEFUNCT_F) VALUES ('PROG_FN_PURCHASEREQ', 'Purchase Requisition', 'N');