/* NUS Restricted */

-- PRSCTABLE
CREATE SYNONYM PRSCTABLE FOR PRSDBM.PRSCTABLE;

-- PRS_TRAN_LOG
CREATE SYNONYM PRS_TRAN_LOG FOR PRSDBM.PRS_TRAN_LOG;
CREATE SYNONYM PRS_TRAN_LOG_SEQ FOR PRSDBM.PRS_TRAN_LOG_SEQ;

-- PRS_INTGR_STATUS
CREATE SYNONYM PRS_INTGR_STATUS FOR PRSDBM.PRS_INTGR_STATUS;
CREATE SYNONYM PRS_INTGR_STS_SEQ FOR PRSDBM.PRS_INTGR_STS_SEQ;