/* NUS Restricted */

-- PRSCTABLE
CREATE SYNONYM PRSCTABLE FOR PRSDBM.PRSCTABLE;

-- PRS_USER_ACCESS
CREATE SYNONYM PRS_USER_ACCESS FOR PRSDBM.PRS_USER_ACCESS;
CREATE SYNONYM PRS_USER_ACCESS_SEQ FOR PRSDBM.PRS_USER_ACCESS_SEQ;

-- PRS_USER_ATTR
CREATE SYNONYM PRS_USER_ATTR FOR PRSDBM.PRS_USER_ATTR;
CREATE SYNONYM PRS_USER_ATTR_SEQ FOR PRSDBM.PRS_USER_ATTR_SEQ;

-- PRS_TRAN_LOG
CREATE SYNONYM PRS_TRAN_LOG FOR PRSDBM.PRS_TRAN_LOG;
CREATE SYNONYM PRS_TRAN_LOG_SEQ FOR PRSDBM.PRS_TRAN_LOG_SEQ;