/* NUS Restricted */

/* ----------------------------------------------------------------------
TABLE: PRS_CURRENCY
---------------------------------------------------------------------- */
CREATE TABLE PRSDBM.PRS_CURRENCY
(
    CRCY_C VARCHAR2(4) NOT NULL,
    CRCY_T VARCHAR2(50) NOT NULL,
    DEFUNCT_F VARCHAR2(1) NOT NULL
)
;

COMMENT ON TABLE PRSDBM.PRS_CURRENCY IS 'Table to store the currencies supported by Sesami for use in LMPRS.';
COMMENT ON COLUMN PRSDBM.PRS_CURRENCY.CRCY_C IS '3 letter ISO currency code as provided by Sesami.';
COMMENT ON COLUMN PRSDBM.PRS_CURRENCY.CRCY_T IS 'Name of currency as provided by Sesami.';
COMMENT ON COLUMN PRSDBM.PRS_CURRENCY.DEFUNCT_F IS 'Flag to denote if this currency has been defunct by Sesami.';

/* ----------------------------------------------------------------------
CONSTRAINT:  Format is SYSTEM_TABLE_KEY_COL(S)
KEY Type: PK (Primary Key), FK (Foreign Key), UK (Unique Key), CK (Constraint), I (INDEX)
---------------------------------------------------------------------- */

ALTER TABLE PRSDBM.PRS_CURRENCY ADD (
CONSTRAINT PRS_PC_PK_CC
PRIMARY KEY (CRCY_C)
);

ALTER TABLE PRSDBM.PRS_CURRENCY ADD (
CONSTRAINT PRS_PC_CK_DF
CHECK (DEFUNCT_F IN ('Y','N'))
);

/* ----------------------------------------------------------------------
GRANT: Who and what privilege to grant
---------------------------------------------------------------------- */
GRANT DELETE, INSERT, SELECT, UPDATE ON PRSDBM.PRS_CURRENCY TO PRJPRS;
GRANT SELECT ON PRSDBM.PRS_CURRENCY TO RPTPRS;

/*
 * Initial population
 */
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('XEU', 'European Currency Unit (E.C.U.)', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('ANG', 'Netherlands Antillian Guilder', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('AED', 'United Arab Emirates Dirham', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('STD', 'Sao Tome And Principe Dobra', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('TTD', 'Trinidad and Tobago Dollar', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('FKP', 'Falkland Islands Pound', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('NIO', 'Nicaraguan Cordoba Oro', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('SBD', 'Solomon Islands Dollar', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('CNY', 'Chinese Yuan Renminbi', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('XCD', 'East Carribean Dollar', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('KYD', 'Cayman Islands Dollar', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('SAR', 'Saudi Arabian Riyal', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('ARA', 'Argentinian Austral', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('MRO', 'Mauritanian Ouguiya', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('SZL', 'Swaziland Lilangeni', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('ATS', 'Austrian Schilling', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('NZD', 'New Zealand Dollar', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('PEN', 'Peruvian Nuevo Sol', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('ZAR', 'South African Rand', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('AON', 'Angolan New Kwanza', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('BOB', 'Bolivian Boliviano', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('GTQ', 'Guatemalan Quetzal', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('MXN', 'Mexican Nuevo Peso', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('MZM', 'Mozambique Metical', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('SHP', 'Saint Helena Pound', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('SLL', 'Sierra Leone Leone', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('TZS', 'Tanzanian Shilling', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('VEB', 'Venezualan Bolivar', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('AUD', 'Australian Dollar', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('IDR', 'Indonesian Rupiah', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('MVR', 'Maldives Rufiyaaa', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('MYR', 'Malaysian Ringgit', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('PTE', 'Portuguese Escudo', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('TWD', 'New Taiwan Dollar', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('BSD', 'Bahamanian Dollar', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('CRC', 'Costa Rican Colon', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('CVE', 'Cape Verde Escudo', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('PAB', 'Panamanian Balboa', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('SVC', 'El Salvador Colon', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('BDT', 'Bangladeshi Taka', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('HKD', 'Hong Kong Dollar', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('HUF', 'Hungarian Forint', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('KRW', 'South Korean Won', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('NOK', 'Norwegian Kroner', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('SCR', 'Seychelles Rupee', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('SGD', 'Singapore Dollar', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('BMD', 'Bermudian Dollar', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('HNL', 'Honduran Lempira', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('KZT', 'Kazakhstan Tenge', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('LTL', 'Lithuanian Litas', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('LUF', 'Luxembourg Franc', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('MGF', 'Madagascar Franc', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('MNT', 'Mongolian Tugrik', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('NPW', 'North Korean Won', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('PGK', 'Papua New Guinea', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('PLN', 'Polish New Zloty', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('PYG', 'Paraguay Guarani', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('SRG', 'Suriname Guilder', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('CAD', 'Canadian Dollar', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('KES', 'Kenyan Shilling', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('LKR', 'Sri Lanka Rupee', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('MUR', 'Mauritius Rupee', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('PHP', 'Philippine Peso', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('VND', 'Vietnamese Dong', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('ADP', 'Andorran Peseta', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('BBD', 'Barbados Dollar', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('BTN', 'Bhutan Ngultrum', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('GIP', 'Gibraltar Pound', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('GYD', 'Guyanese Dollar', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('JMD', 'Jamaican Dollar', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('JOD', 'Jordanian Dinar', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('LRD', 'Liberian Dollar', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('MAD', 'Moroccan Dirham', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('SIT', 'Slovenian Tolar', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('SOS', 'Somali Shilling', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('UAH', 'Ukraine Hryvnia', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('UGS', 'Uganda Shilling', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('ZWD', 'Zimbabwe Dollar', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('BRL', 'Brazilian Real', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('ESP', 'Spanish Peseta', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('FIM', 'Finnish Markka', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('GBP', 'Pound Sterling', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('ILS', 'Israeli Shekel', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('NGN', 'Nigerian Naira', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('PKR', 'Pakistan Rupee', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('ADF', 'Andorran Franc', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('ARS', 'Argentine Peso', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('BHD', 'Bahraini Dinar', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('COP', 'Columbian Peso', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('DJF', 'Djibouti Franc', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('DOP', 'Dominican Peso', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('DZD', 'Algerian Dinar', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('EEK', 'Estonian Kroon', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('EGP', 'Egyptian Pound', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('ETB', 'Ethiopian Birr', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('GMD', 'Gambian Dalasi', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('HTG', 'Haitian Gourde', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('KHR', 'Cambodian Riel', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('LBP', 'Lenanese Pound', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('NAD', 'Namibia Dollar', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('NPR', 'Nepalese Rupee', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('TND', 'Tunisian Dinar', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('UYP', 'Uruguayan Peso', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('ZMK', 'Zambian Kwacha', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('BEF', 'Belgian Franc', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('BND', 'Brunei Dollar', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('DEM', 'Deutsche Mark', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('GHC', 'Ghanaian Cedi', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('KWD', 'Kuwaiti Dinar', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('NLG', 'Dutch Guilder', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('SEK', 'Swedish Krona', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('AWG', 'Aruban Florin', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('BGL', 'Bulgarian Lev', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('BIF', 'Burundi Franc', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('BWP', 'Botswana Pula', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('BZD', 'Belize Dollar', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('ECS', 'Ecuador Sucre', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('GRD', 'Greek Drachma', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('HRK', 'Croatian Kuna', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('ISK', 'Iceland Krona', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('KMF', 'Comoros Franc', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('MWK', 'Malawi Kwacha', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('PEI', 'Peruvian Inti', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('RUB', 'Russian Ruble', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('SKK', 'Slovak Koruna', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('TOP', 'Tonga Pa''anga', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('DKK', 'Danish Krone', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('FRF', 'French Franc', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('INR', 'Indian Rupee', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('ITL', 'Italian Lira', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('JPY', 'Japanese Yen', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('MMK', 'Myanmar Kyat', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('TRL', 'Turkish Lira', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('ALL', 'Albanian Lek', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('CLP', 'Chilean Peso', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('CSK', 'Czech Koruna', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('CYP', 'Cyprus Pound', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('GNF', 'Guinea Franc', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('LAK', 'Laothian Kip', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('LSL', 'Lesotho Loti', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('LVL', 'Latvian Lats', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('LYD', 'Libyan Dinar', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('MOP', 'Macau Pataca', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('MTL', 'Maltese Lira', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('PLZ', 'Polish Zloty', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('ROL', 'Romanian Leu', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('SYP', 'Syrian Potmd', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('VUV', 'Vanuatu Vatu', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('CHF', 'Swiss Franc', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('QAR', 'Qatari Rial', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('USD', 'U.S. Dollar', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('FJD', 'Fiji Dollar', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('IQR', 'Iraqi Dinar', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('WST', 'Samoan Tala', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('YER', 'Yemeni Rial', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('OMR', 'Omani Rial', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('IEP', 'Irish Punt', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('THB', 'Thai Baht', 'N');
INSERT INTO PRS_CURRENCY (CRCY_C, CRCY_T, DEFUNCT_F) VALUES('EUR', 'Euro', 'N');
