
CREATE OR REPLACE SYNONYM PRS_QUOTATION_DOCUMENT FOR PRSDBM.PRS_QUOTATION_DOCUMENT;
CREATE OR REPLACE SYNONYM PRS_REQ_DOCUMENT FOR PRSDBM.PRS_REQ_DOCUMENT;
CREATE OR REPLACE SYNONYM PRS_APPV_LMT FOR PRSDBM.PRS_APPV_LMT;
CREATE OR REPLACE SYNONYM PRS_APPV_LMT_SEQ FOR PRSDBM.PRS_APPV_LMT_SEQ;