
ALTER TABLE PRS_PURCHASE_REQ ADD REQ_ROLETP_C VARCHAR2(50);

UPDATE PRS_PURCHASE_REQ SET REQ_ROLETP_C = 'ROLE_PRINCIPAL_INVESTIGATOR';

ALTER TABLE PRS_PURCHASE_REQ MODIFY (REQ_ROLETP_C NOT NULL);

ALTER TABLE PRSDBM.PRS_PURCHASE_REQ ADD (
CONSTRAINT PRS_PRR_FK_RTC
    FOREIGN KEY (REQ_ROLETP_C)
        REFERENCES PRSDBM.PRSCTABLE(CODE_C)
);