
-- Add abbreviation for unit of measurement
ALTER TABLE IISDBM.MSRUNIT ADD MSRUNIT_T1 NVARCHAR2(3);
COMMENT ON COLUMN IISDBM.MSRUNIT.MSRUNIT_T1 IS 'Short text (abbreviation) for unit of measurement';

-- Populate abbreviation
INSERT INTO MSRUNIT VALUES ('24','BOX',NULL);

UPDATE MSRUNIT SET MSRUNIT_T1 = 'cm³' 	WHERE MSRUNIT_C = '19';
UPDATE MSRUNIT SET MSRUNIT_T1 = 'm³' 	WHERE MSRUNIT_C = '18';
UPDATE MSRUNIT SET MSRUNIT_T1 = 'g' 	WHERE MSRUNIT_C = '4';
UPDATE MSRUNIT SET MSRUNIT_T1 = 'kg' 	WHERE MSRUNIT_C = '15';
UPDATE MSRUNIT SET MSRUNIT_T1 = 'L' 	WHERE MSRUNIT_C = '12';
UPDATE MSRUNIT SET MSRUNIT_T1 = 'µg' 	WHERE MSRUNIT_C = '17';
UPDATE MSRUNIT SET MSRUNIT_T1 = 'µL' 	WHERE MSRUNIT_C = '14';
UPDATE MSRUNIT SET MSRUNIT_T1 = 'mg' 	WHERE MSRUNIT_C = '16';
UPDATE MSRUNIT SET MSRUNIT_T1 = 'mL' 	WHERE MSRUNIT_C = '13';
UPDATE MSRUNIT SET MSRUNIT_T1 = 'gal' 	WHERE MSRUNIT_C = '22';
UPDATE MSRUNIT SET MSRUNIT_T1 = 'EA' 	WHERE MSRUNIT_C = '23';
UPDATE MSRUNIT SET MSRUNIT_T1 = 'KU' 	WHERE MSRUNIT_C = '21';
UPDATE MSRUNIT SET MSRUNIT_T1 = 'MU' 	WHERE MSRUNIT_C = '20';