/* NUS Restricted */

-- PRS_JOB_EXECUTION
CREATE SYNONYM PRS_JOB_EXECUTION FOR PRSDBM.PRS_JOB_EXECUTION;

-- PRS_JOB_EXECUTION_PARAMS
CREATE SYNONYM PRS_JOB_EXECUTION_PARAMS FOR PRSDBM.PRS_JOB_EXECUTION_PARAMS;

-- PRS_JOB_EXECUTION_CONTEXT
CREATE SYNONYM PRS_JOB_EXECUTION_CONTEXT FOR PRSDBM.PRS_JOB_EXECUTION_CONTEXT;

-- PRS_STEP_EXECUTION
CREATE SYNONYM PRS_STEP_EXECUTION FOR PRSDBM.PRS_STEP_EXECUTION;

-- PRS_STEP_EXECUTION_CONTEXT
CREATE SYNONYM PRS_STEP_EXECUTION_CONTEXT FOR PRSDBM.PRS_STEP_EXECUTION_CONTEXT;

-- PRS_JOB_INSTANCE
CREATE SYNONYM PRS_JOB_INSTANCE FOR PRSDBM.PRS_JOB_INSTANCE;

-- SEQUENCES
CREATE SYNONYM PRS_JOB_SEQ FOR PRSDBM.PRS_JOB_SEQ;
CREATE SYNONYM PRS_JOB_EXECUTION_SEQ FOR PRSDBM.PRS_JOB_EXECUTION_SEQ;
CREATE SYNONYM PRS_STEP_EXECUTION_SEQ FOR PRSDBM.PRS_STEP_EXECUTION_SEQ;
