/* ----------------------------------------------------------------------
Purpose : For GR de-link
Date : 2019-07-19
---------------------------------------------------------------------- */
CREATE TABLE PRS_PO_INVENTORY (
    LINEITEM_INVNT_N   VARCHAR2(11) NOT NULL,
    INVNT_QTY_Q        NUMBER NOT NULL,
    LINEITEM_N         VARCHAR2(11) NOT NULL,
    RT_ITEM_N          VARCHAR2(11) NOT NULL
);
--TABLESPACE S1_DAT;
COMMENT ON TABLE PRSDBM.PRS_PO_INVENTORY IS 'Table stores the quantity of items that has been inventoried in LMMS for a PO line item.';
COMMENT ON COLUMN PRSDBM.PRS_PO_INVENTORY.LINEITEM_INVNT_N IS 'Primay key - Generated by Oracle Sequence number.';
COMMENT ON COLUMN PRSDBM.PRS_PO_INVENTORY.INVNT_QTY_Q IS 'The inventory quantity the has been added into LMMS';
COMMENT ON COLUMN PRSDBM.PRS_PO_INVENTORY.LINEITEM_N IS 'Refer to PO line item number';
COMMENT ON COLUMN PRSDBM.PRS_PO_INVENTORY.RT_ITEM_N IS 'Refer to Goods receipt line item number';

ALTER TABLE PRSDBM.PRS_PO_INVENTORY ADD CONSTRAINT PRS_POI_PK_LN PRIMARY KEY ( LINEITEM_INVNT_N );--TABLESPACE S1_IDX

ALTER TABLE PRSDBM.PRS_PO_INVENTORY ADD CONSTRAINT PRS_PO_POI_FK_LN FOREIGN KEY ( LINEITEM_N )
    REFERENCES PRSDBM.PRS_PO_LINEITEM ( LINEITEM_N );--TABLESPACE S1_IDX

ALTER TABLE PRSDBM.PRS_PO_INVENTORY ADD CONSTRAINT PRS_RT_POI_FK_RI FOREIGN KEY ( RT_ITEM_N )
    REFERENCES PRSDBM.PRS_RECEIPT_LINEITEM ( RT_ITEM_N );--TABLESPACE S1_IDX
	
	
/* ----------------------------------------------------------------------
GRANT: Who and what privilege to grant
---------------------------------------------------------------------- */
GRANT DELETE, INSERT, SELECT, UPDATE ON PRSDBM.PRS_PO_INVENTORY TO PRJPRS;
GRANT SELECT ON PRSDBM.PRS_PO_INVENTORY TO RPTPRS;


/* ----------------------------------------------------------------------
SEQUENCE
---------------------------------------------------------------------- */
CREATE SEQUENCE PRSDBM.PRS_PO_INVENTORY_SEQ
    START WITH 1
    MINVALUE 1
    INCREMENT BY 1
    NOCYCLE
    NOCACHE;

/* ----------------------------------------------------------------------
GRANT: Who and what privilege to grant
---------------------------------------------------------------------- */
GRANT SELECT ON PRSDBM.PRS_PO_INVENTORY_SEQ TO PRJPRS;
GRANT SELECT ON PRSDBM.PRS_PO_INVENTORY_SEQ TO RPTPRS;
