/* ----------------------------------------------------------------------
SYNONYM: PRS_PO_LMMSINVTRY, PRS_PO_LMMSINVTRY_SEQ
---------------------------------------------------------------------- */
CREATE OR REPLACE SYNONYM PRS_INTERNAL_STORE FOR PRSDBM.PRS_INTERNAL_STORE;
CREATE OR REPLACE SYNONYM PRS_USER_ACCESSTP FOR PRSDBM.PRS_USER_ACCESSTP;
CREATE OR REPLACE SYNONYM PRS_COLLECTION FOR PRSDBM.PRS_COLLECTION;
CREATE OR REPLACE SYNONYM PRS_COLLECTION_REMARK FOR PRSDBM.PRS_COLLECTION_REMARK;

CREATE OR REPLACE SYNONYM PRS_INTERNAL_STORE_SEQ FOR PRSDBM.PRS_INTERNAL_STORE_SEQ;
CREATE OR REPLACE SYNONYM PRS_USER_ACCESSTP_SEQ FOR PRSDBM.PRS_USER_ACCESSTP_SEQ;
CREATE OR REPLACE SYNONYM PRS_COLLECTION_SEQ FOR PRSDBM.PRS_COLLECTION_SEQ;
CREATE OR REPLACE SYNONYM PRS_COLLECTION_REMARK_SEQ FOR PRSDBM.PRS_COLLECTION_REMARK_SEQ;

