/* NUS Restricted */

-- PRS_SUPPLIER
CREATE SYNONYM PRS_SUPPLIER FOR PRSDBM.PRS_SUPPLIER;

-- PRS_INTGR_STS
CREATE SYNONYM PRS_INTGR_STS FOR PRSDBM.PRS_INTGR_STS;
CREATE SYNONYM PRS_INTGR_STS_SEQ FOR PRSDBM.PRS_INTGR_STS_SEQ;

-- PRS_COUNTRY
CREATE SYNONYM PRS_COUNTRY FOR PRSDBM.PRS_COUNTRY;
