/* ----------------------------------------------------------------------
Purpose : add GL Account Type
Date : 2019-10-07
---------------------------------------------------------------------- */

INSERT INTO PRSDBM.PRSCTABLE (CODE_C, CODE_T, DEFUNCT_F) VALUES ('GL_TYPE_INTL_SUPPLIER', 'Internal Supplier', 'N');

INSERT INTO PRSDBM.PRSCTABLE (CODE_C, CODE_T, DEFUNCT_F) VALUES ('GL_TYPE_EXT_SUPPLIER', 'External Supplier', 'N');

ALTER TABLE PRSDBM.PRSGLAC ADD GL_ACTP_C VARCHAR2(50 BYTE);

COMMENT ON COLUMN PRSDBM.PRSGLAC.GL_ACTP_C IS 'GL Account type.';

ALTER TABLE PRSDBM.PRSGLAC ADD CONSTRAINT PRS_GLAC_FK_CC FOREIGN KEY ( GL_ACTP_C ) REFERENCES PRSCTABLE ( CODE_C );

UPDATE PRSDBM.PRSGLAC SET GL_ACTP_C = 'GL_TYPE_EXT_SUPPLIER';

ALTER TABLE PRSDBM.PRSGLAC MODIFY (GL_ACTP_C NOT NULL);

INSERT INTO PRSDBM.PRSGLAC (GL_AC_N, DEFAULT_F, DEFUNCT_F, GL_AC_T, GL_ACTP_C) VALUES ('791407', 'N', 'N', 'Expenditure-Inter-Dept (For Lab Store)', 'GL_TYPE_INTL_SUPPLIER');