-- Internal stores
INSERT INTO PRS_INTERNAL_STORE (INTL_STORE_N, SUPP_C, WBS_AC_N, GL_AC_N, CHM_LOC_N, FAC_C, DEPT_C, DEFUNCT_F, REC_CREATEUSER_I, REC_CREATE_DTM, REC_UPDUSER_I, REC_UPD_DTM) 
VALUES (PRS_INTERNAL_STORE_SEQ.nextVal, 'NUSNTP0000109667', 'N-143-000-010-001', '539407', '100000194-100000596', '32', '143', 'N', 'LMPRS', sysdate, 'LMPRS', sysdate);

--INSERT INTO PRS_INTERNAL_STORE (INTL_STORE_N, SUPP_C, WBS_AC_N, GL_AC_N, CHM_LOC_N, FAC_C, DEPT_C, DEFUNCT_F, REC_CREATEUSER_I, REC_CREATE_DTM, REC_UPDUSER_I, REC_UPD_DTM) 
--VALUES (PRS_INTERNAL_STORE_SEQ.nextVal, 'DUMMYSUPPLIER01', 'C-171-014-000-001', '539407', '100000194-100000596', '43', '568', 'N', 'LMPRS', sysdate, 'LMPRS', sysdate);


-- Audit log function name
INSERT INTO PRSCTABLE (CODE_C, CODE_T, DEFUNCT_F) VALUES ('PROG_FN_INTERNAL_PROCUREMENT', 'Internal Procurement', 'N'); 

-- Journal type
INSERT INTO PRSCTABLE (CODE_C, CODE_T, DEFUNCT_F) VALUES ('JRNL_DEBIT', 'Debit', 'N');
INSERT INTO PRSCTABLE (CODE_C, CODE_T, DEFUNCT_F) VALUES ('JRNL_CREDIT', 'Credit', 'N');

-- New role for Vice President
Insert into PRSCTABLE (CODE_C,CODE_T,DEFUNCT_F) values ('ROLE_VICE_PRESIDENT','Vice President','N');

-- New user attribute for lab supply officer
Insert into PRSCTABLE (CODE_C,CODE_T,DEFUNCT_F) values ('USER_ATTR_INTERNAL_STORE','Internal Store','N');
