--Purpose : Purchase Request Tables
--   Date : 21 March 2019
CREATE OR REPLACE SYNONYM PRS_PR_PURCH_REQ FOR PRSDBM.PRS_PR_PURCH_REQ;
CREATE OR REPLACE SYNONYM PRS_PR_LINEITEM FOR PRSDBM.PRS_PR_LINEITEM;
CREATE OR REPLACE SYNONYM PRS_PR_LINEITEM_PRDC FOR PRSDBM.PRS_PR_LINEITEM_PRDC;
CREATE OR REPLACE SYNONYM PRS_PR_AC_ASSIGN FOR PRSDBM.PRS_PR_AC_ASSIGN;
CREATE OR REPLACE SYNONYM PRS_PR_QT FOR PRSDBM.PRS_PR_QT;
CREATE OR REPLACE SYNONYM PRS_PR_DOCU FOR PRSDBM.PRS_PR_DOCU;
CREATE OR REPLACE SYNONYM PRS_PR_QT_AWARD FOR PRSDBM.PRS_PR_QT_AWARD;
CREATE OR REPLACE SYNONYM PRS_PR_DELIVERY_INFO FOR PRSDBM.PRS_PR_DELIVERY_INFO;
CREATE OR REPLACE SYNONYM PRS_PR_SYSTEM_CHECK FOR PRSDBM.PRS_PR_SYSTEM_CHECK;
CREATE OR REPLACE SYNONYM PRS_USER_PREF FOR PRSDBM.PRS_USER_PREF;

CREATE OR REPLACE SYNONYM PRS_PR_PURCHASE_REQUEST_SEQ FOR PRSDBM.PRS_PR_PURCHASE_REQUEST_SEQ;
CREATE OR REPLACE SYNONYM PRS_PR_LINEITEM_SEQ FOR PRSDBM.PRS_PR_LINEITEM_SEQ;
CREATE OR REPLACE SYNONYM PRS_PR_LINEITEM_PRODUCT_SEQ FOR PRSDBM.PRS_PR_LINEITEM_PRODUCT_SEQ;
CREATE OR REPLACE SYNONYM PRS_PR_ACASSIGN_SEQ FOR PRSDBM.PRS_PR_ACASSIGN_SEQ;
CREATE OR REPLACE SYNONYM PRS_PR_QUOTATION_SEQ FOR PRSDBM.PRS_PR_QUOTATION_SEQ;
CREATE OR REPLACE SYNONYM PRS_PR_DOCUMENT_SEQ FOR PRSDBM.PRS_PR_DOCUMENT_SEQ;
CREATE OR REPLACE SYNONYM PRS_PR_AWARD_SEQ FOR PRSDBM.PRS_PR_AWARD_SEQ;
CREATE OR REPLACE SYNONYM PRS_PR_DELVINFO_SEQ FOR PRSDBM.PRS_PR_DELVINFO_SEQ;
CREATE OR REPLACE SYNONYM PRS_PR_SYSCHK_SEQ FOR PRSDBM.PRS_PR_SYSCHK_SEQ;
CREATE OR REPLACE SYNONYM PRS_PR_PRNUMBER_SEQ FOR PRSDBM.PRS_PR_PRNUMBER_SEQ;
CREATE OR REPLACE SYNONYM PRS_PR_AORNUMBER_SEQ FOR PRSDBM.PRS_PR_AORNUMBER_SEQ;
CREATE OR REPLACE SYNONYM PRS_PR_USERPREF_SEQ FOR PRSDBM.PRS_PR_USERPREF_SEQ;