/* NUS Restricted */

-- PRS_API_CONFIG
CREATE OR REPLACE SYNONYM PRS_API_CONFIG FOR PRSDBM.PRS_API_CONFIG;

-- PRS_API_CONFIG_SEQ
CREATE OR REPLACE SYNONYM PRS_API_CONFIG_SEQ FOR PRSDBM.PRS_API_CONFIG_SEQ;