/* NUS Restricted */

/* ----------------------------------------------------------------------
TABLE: PRS_API_CONFIG
---------------------------------------------------------------------- */
CREATE TABLE PRSDBM.PRS_API_CONFIG
(
    API_N VARCHAR2(11) NOT NULL,
    APP_T VARCHAR2(64) NOT NULL,
    KEY_T VARCHAR2(64) NOT NULL,
    URL_T VARCHAR2(200) NOT NULL,
    RMK_T VARCHAR2(1000) NOT NULL,
    VLD_ST_DTM  DATE NOT NULL,
	VLD_END_DTM  DATE NOT NULL,
	REC_UPDUSER_I VARCHAR2(20) NOT NULL,
	REC_UPD_DTM DATE NOT NULL
)
;

COMMENT ON TABLE PRSDBM.PRS_API_CONFIG IS 'This table stores API key configuration in hashed form. This configuration controls which applications can call the PRS application.';
COMMENT ON COLUMN PRSDBM.PRS_API_CONFIG.API_N IS 'Primary key of record. Generated by Oracle sequence.';
COMMENT ON COLUMN PRSDBM.PRS_API_CONFIG.APP_T IS 'Application ID. This value is passed in via the X-APP-API header.';
COMMENT ON COLUMN PRSDBM.PRS_API_CONFIG.KEY_T IS 'Hashed value of API key. Original value will be passed via header X-LMPRS-API.';
COMMENT ON COLUMN PRSDBM.PRS_API_CONFIG.URL_T IS 'URL prefix this API key is allowed access to.';
COMMENT ON COLUMN PRSDBM.PRS_API_CONFIG.RMK_T IS 'Remarks to indicate the purposeand to whom and the API key is assigned to.';
COMMENT ON COLUMN PRSDBM.PRS_API_CONFIG.VLD_ST_DTM IS 'Start date of the validity period for the API key.';
COMMENT ON COLUMN PRSDBM.PRS_API_CONFIG.VLD_END_DTM IS 'End date of the validity period for the API key.';
COMMENT ON COLUMN PRSDBM.PRS_API_CONFIG.REC_UPDUSER_I IS 'User who last updated the record.';
COMMENT ON COLUMN PRSDBM.PRS_API_CONFIG.REC_UPD_DTM IS 'The date and time this record was last updated.';

/* ----------------------------------------------------------------------
CONSTRAINT:  Format is SYSTEM_TABLE_KEY_COL(S)
KEY Type: PK (Primary Key), FK (Foreign Key), UK (Unique Key), CK (Constraint), I (INDEX)
---------------------------------------------------------------------- */

ALTER TABLE PRSDBM.PRS_API_CONFIG ADD (
CONSTRAINT PRS_PAC_PK_AN
PRIMARY KEY (API_N)
);

/* ----------------------------------------------------------------------
GRANT: Who and what privilege to grant
---------------------------------------------------------------------- */
GRANT DELETE, INSERT, SELECT, UPDATE ON PRSDBM.PRS_API_CONFIG TO PRJPRS;
GRANT SELECT ON PRSDBM.PRS_API_CONFIG TO RPTPRS;

/*
 * Sequences
 */
CREATE SEQUENCE PRSDBM.PRS_API_CONFIG_SEQ;
GRANT SELECT ON PRSDBM.PRS_API_CONFIG_SEQ TO PRJPRS;
GRANT SELECT ON PRSDBM.PRS_API_CONFIG_SEQ TO RPTPRS;