

INSERT INTO PRSDBM.PRSCTABLE (CODE_C, CODE_T, DEFUNCT_F) VALUES ('PERIOD_CTRCT_CAT_SOLVENT', 'Solvent', 'N');
INSERT INTO PRSDBM.PRSCTABLE (CODE_C, CODE_T, DEFUNCT_F) VALUES ('PERIOD_CTRCT_CAT_CHEMICAL', 'Chemical', 'N');
INSERT INTO PRSDBM.PRSCTABLE (CODE_C, CODE_T, DEFUNCT_F) VALUES ('PERIOD_CTRCT_CAT_ANB', 'Acid and Base', 'N');
INSERT INTO PRSDBM.PRSCTABLE (CODE_C, CODE_T, DEFUNCT_F) VALUES ('PERIOD_CTRCT_CAT_DSOLVENT', 'Deuterated Solvent', 'N');

INSERT INTO PRSDBM.PRSCTABLE (CODE_C, CODE_T, DEFUNCT_F) VALUES ('PERIOD_CTRCT_AC_CAMPUS', 'Campus', 'N');
INSERT INTO PRSDBM.PRSCTABLE (CODE_C, CODE_T, DEFUNCT_F) VALUES ('PERIOD_CTRCT_AC_FAC', 'Faculty', 'N');
INSERT INTO PRSDBM.PRSCTABLE (CODE_C, CODE_T, DEFUNCT_F) VALUES ('PERIOD_CTRCT_AC_DEPT', 'Department', 'N'); 

INSERT INTO PRSDBM.PRSCTABLE (CODE_C, CODE_T, DEFUNCT_F) VALUES ('PERIOD_CTRCT_CT_NUS', 'Nus', 'N');
INSERT INTO PRSDBM.PRSCTABLE (CODE_C, CODE_T, DEFUNCT_F) VALUES ('PERIOD_CTRCT_CT_OTHER', 'Others', 'N'); 

INSERT INTO PRSDBM.PRSCTABLE (CODE_C, CODE_T, DEFUNCT_F) VALUES ('PERIOD_CTRCT_STS_DRAFT', 'Draft', 'N');
INSERT INTO PRSDBM.PRSCTABLE (CODE_C, CODE_T, DEFUNCT_F) VALUES ('PERIOD_CTRCT_STS_PUBLISH', 'Published', 'N');
INSERT INTO PRSDBM.PRSCTABLE (CODE_C, CODE_T, DEFUNCT_F) VALUES ('PERIOD_CTRCT_STS_UNPUBLISH', 'Unpublished', 'N');
INSERT INTO PRSDBM.PRSCTABLE (CODE_C, CODE_T, DEFUNCT_F) VALUES ('PERIOD_CTRCT_STS_DEFUNCT', 'Defunct', 'N');

INSERT INTO PRSDBM.PRSCTABLE (CODE_C, CODE_T, DEFUNCT_F) VALUES ('PROG_FN_PERIOD_CONTRACT', 'Period Contract', 'N');

INSERT INTO PRSDBM.PRSCTABLE (CODE_C, CODE_T, DEFUNCT_F) VALUES ('USER_ATTR_PERIOD_CONTRACT_LEVEL', 'Period Contract Level', 'N');

INSERT INTO PRSDBM.PRSCTABLE (CODE_C, CODE_T, DEFUNCT_F) VALUES ('PERIOD_CONTRACT_LEVEL_NUS', 'NUS', 'N');
INSERT INTO PRSDBM.PRSCTABLE (CODE_C, CODE_T, DEFUNCT_F) VALUES ('PERIOD_CONTRACT_LEVEL_FAC', 'Faculty', 'N');
INSERT INTO PRSDBM.PRSCTABLE (CODE_C, CODE_T, DEFUNCT_F) VALUES ('PERIOD_CONTRACT_LEVEL_DEPT', 'Department', 'N');

INSERT INTO PRSDBM.PRSCTABLE (CODE_C, CODE_T, DEFUNCT_F) VALUES ('ROLE_CATALOGUE_ADMIN', 'Catalogue Administrator', 'N');