--Purpose : Period Contract Tables
/* ----------------------------------------------------------------------
TABLE: PRS_PERIOD_CTRCT => PRS_PERIODCONTRACT_PARTICS
---------------------------------------------------------------------- */

CREATE TABLE PRSDBM.PRS_PERIODCONTRACT_PARTICS
  (
    PRDCON_SEQ_N   VARCHAR2 (11) NOT NULL ,
    CON_N       VARCHAR2 (20) NOT NULL ,
    CON_A       NUMBER (10,2) ,
    CRCY_C           VARCHAR2 (4) ,
    CON_DESC_T  VARCHAR2 (255) ,
    CON_ST_D    DATE ,
    CON_END_D   DATE ,
    CON_LVL_C  VARCHAR2 (50) ,
    CON_TP_C    VARCHAR2 (50) ,
    CON_CAT_C   VARCHAR2 (50) ,
    CON_STS_C   VARCHAR2 (50) ,
    REC_CREATE_DTM   DATE NOT NULL,
    REC_UPD_DTM      DATE ,
    REC_CREATEUSER_I VARCHAR2 (12) NOT NULL,
    REC_UPDUSER_I    VARCHAR2 (12)
  ) ;

COMMENT ON TABLE PRSDBM.PRS_PERIODCONTRACT_PARTICS IS 'This table maintains the details of the period contracts in the Purchase Requisition System (PRS)' ;
COMMENT ON COLUMN PRSDBM.PRS_PERIODCONTRACT_PARTICS.PRDCON_SEQ_N IS 'Auto generated seq no' ;
COMMENT ON COLUMN PRSDBM.PRS_PERIODCONTRACT_PARTICS.CON_N IS 'Unique Contract Number' ;
COMMENT ON COLUMN PRSDBM.PRS_PERIODCONTRACT_PARTICS.CON_A IS 'Contract Value' ;
COMMENT ON COLUMN PRSDBM.PRS_PERIODCONTRACT_PARTICS.CRCY_C IS 'Currency code for procurement purposes. It references PRSCURRENCY table.' ;
COMMENT ON COLUMN PRSDBM.PRS_PERIODCONTRACT_PARTICS.CON_DESC_T IS 'Contract Description' ;
COMMENT ON COLUMN PRSDBM.PRS_PERIODCONTRACT_PARTICS.CON_ST_D IS 'Contract Start Date' ;
COMMENT ON COLUMN PRSDBM.PRS_PERIODCONTRACT_PARTICS.CON_END_D IS 'Contract End Date' ;
COMMENT ON COLUMN PRSDBM.PRS_PERIODCONTRACT_PARTICS.CON_LVL_C IS 'Contract Level Code, whether it is applicable for Campus (C), Faculty (F), Department (D). It references the common reference/lookup table INTLCURRENCY)' ;
COMMENT ON COLUMN PRSDBM.PRS_PERIODCONTRACT_PARTICS.CON_TP_C IS 'Contract Type (NUS/Other)(Reference to PRSCTABLE)' ;
COMMENT ON COLUMN PRSDBM.PRS_PERIODCONTRACT_PARTICS.CON_CAT_C IS 'Contract Category(Reference to PRSCTABLE)' ;
COMMENT ON COLUMN PRSDBM.PRS_PERIODCONTRACT_PARTICS.CON_STS_C IS 'Contract Status Code (eg: Draft, Published, Defunct) (Reference to PRSCTABLE)' ;
COMMENT ON COLUMN PRSDBM.PRS_PERIODCONTRACT_PARTICS.REC_CREATE_DTM IS 'Record Created Date' ;
COMMENT ON COLUMN PRSDBM.PRS_PERIODCONTRACT_PARTICS.REC_UPD_DTM IS 'Record Updated Date' ;
COMMENT ON COLUMN PRSDBM.PRS_PERIODCONTRACT_PARTICS.REC_CREATEUSER_I IS 'Record Created User' ;
COMMENT ON COLUMN PRSDBM.PRS_PERIODCONTRACT_PARTICS.REC_UPDUSER_I IS 'Record Updated User' ;


 
  
  ALTER TABLE PRSDBM.PRS_PERIODCONTRACT_PARTICS ADD CONSTRAINT PRS_PCP_PK_PC PRIMARY KEY ( PRDCON_SEQ_N ) ;
  ALTER TABLE PRSDBM.PRS_PERIODCONTRACT_PARTICS ADD CONSTRAINT PRS_PCP_UN_CN UNIQUE ( CON_N ) ;
  ALTER TABLE PRSDBM.PRS_PERIODCONTRACT_PARTICS ADD CONSTRAINT PRS_PCP_FK_CL FOREIGN KEY ( CON_LVL_C ) REFERENCES PRSDBM.PRSCTABLE ( CODE_C ) ;
  ALTER TABLE PRSDBM.PRS_PERIODCONTRACT_PARTICS ADD CONSTRAINT PRS_PCP_FK_CC FOREIGN KEY ( CRCY_C ) REFERENCES PRSDBM.PRSCURRENCY ( CRCY_C ) ;
  ALTER TABLE PRSDBM.PRS_PERIODCONTRACT_PARTICS ADD CONSTRAINT PRS_PCP_FK_CA FOREIGN KEY ( CON_CAT_C ) REFERENCES PRSDBM.PRSCTABLE ( CODE_C ) ;
  ALTER TABLE PRSDBM.PRS_PERIODCONTRACT_PARTICS ADD CONSTRAINT PRS_PCP_FK_CS FOREIGN KEY ( CON_STS_C ) REFERENCES PRSDBM.PRSCTABLE ( CODE_C ) ;
  ALTER TABLE PRSDBM.PRS_PERIODCONTRACT_PARTICS ADD CONSTRAINT PRS_PCP_FK_CT FOREIGN KEY ( CON_TP_C ) REFERENCES PRSDBM.PRSCTABLE ( CODE_C ) ;
 
 
 /* ----------------------------------------------------------------------
TABLE: PRS_CTRCT_SUPPLIER => PRS_PRDCONTRACT_SUPPLIER
---------------------------------------------------------------------- */
CREATE TABLE PRSDBM.PRS_PRDCONTRACT_SUPPLIER
  (
    SUPP_N         	VARCHAR2 (11) NOT NULL ,
    PRDCON_SEQ_N 	VARCHAR2 (11) NOT NULL ,
    SUPP_C         	VARCHAR2 (30) NOT NULL ,
    CRCY_C         	VARCHAR2 (4)
  ) ;

COMMENT ON TABLE PRSDBM.PRS_PRDCONTRACT_SUPPLIER IS 'This table maintains the supplier details of the period contract in the Purchase Requisition System (PRS)' ;
COMMENT ON COLUMN PRSDBM.PRS_PRDCONTRACT_SUPPLIER.SUPP_N IS 'Auto generated seq no' ;
COMMENT ON COLUMN PRSDBM.PRS_PRDCONTRACT_SUPPLIER.PRDCON_SEQ_N IS 'Contract Seq no (Reference to PRS_PERIODCONTRACT_PARTICS)' ;
COMMENT ON COLUMN PRSDBM.PRS_PRDCONTRACT_SUPPLIER.SUPP_C IS 'Supplier Code (Reference to PRSSUPPLIER)' ;
COMMENT ON COLUMN PRSDBM.PRS_PRDCONTRACT_SUPPLIER.CRCY_C IS 'Currency code for procurement purposes. It references PRSCURRENCY table.' ;

  
  ALTER TABLE PRSDBM.PRS_PRDCONTRACT_SUPPLIER ADD CONSTRAINT PRS_PCS_PK_SN PRIMARY KEY ( SUPP_N ) ;
  ALTER TABLE PRSDBM.PRS_PRDCONTRACT_SUPPLIER ADD CONSTRAINT PRS_PCS_FK_CC FOREIGN KEY ( CRCY_C ) REFERENCES PRSDBM.PRSCURRENCY ( CRCY_C ) ;
  ALTER TABLE PRSDBM.PRS_PRDCONTRACT_SUPPLIER ADD CONSTRAINT PRS_PCS_FK_PC FOREIGN KEY ( PRDCON_SEQ_N ) REFERENCES PRSDBM.PRS_PERIODCONTRACT_PARTICS ( PRDCON_SEQ_N ) ;
  ALTER TABLE PRSDBM.PRS_PRDCONTRACT_SUPPLIER ADD CONSTRAINT PRS_PCS_FK_SP FOREIGN KEY ( SUPP_C ) REFERENCES PRSDBM.PRSSUPPLIER ( SUPP_C ) ;
 
 
  /* ----------------------------------------------------------------------
TABLE: PRS_CTRCT_SUPPLIERADDCHARGES => PRS_PRDCONTRACT_ADDLCHARGE
---------------------------------------------------------------------- */
CREATE TABLE PRSDBM.PRS_PRODCONTRACT_ADDLCHARGE
  (
    SUPP_ADDlCHRG_N VARCHAR2 (11) NOT NULL ,
    SUPP_N         VARCHAR2 (11) NOT NULL ,
    ADDL_CHRG_T     VARCHAR2 (255) ,
    ADDL_CHRG_A     NUMBER (10,2)
  ) ;

COMMENT ON TABLE PRSDBM.PRS_PRODCONTRACT_ADDLCHARGE IS 'This table maintains the additional charges details of the period contract' ;
COMMENT ON COLUMN PRSDBM.PRS_PRODCONTRACT_ADDLCHARGE.SUPP_ADDlCHRG_N IS 'Auto generated seq no' ;
COMMENT ON COLUMN PRSDBM.PRS_PRODCONTRACT_ADDLCHARGE.SUPP_N IS 'Supplier No (Reference to PRS_PRDCONTRACT_SUPPLIER)' ;
COMMENT ON COLUMN PRSDBM.PRS_PRODCONTRACT_ADDLCHARGE.ADDL_CHRG_T IS 'Additional charge text' ;
COMMENT ON COLUMN PRSDBM.PRS_PRODCONTRACT_ADDLCHARGE.ADDL_CHRG_A IS 'Additional charge amount' ;

 ALTER TABLE PRSDBM.PRS_PRODCONTRACT_ADDLCHARGE ADD CONSTRAINT PRS_PPA_PK_AC PRIMARY KEY ( SUPP_ADDlCHRG_N ) ;
 ALTER TABLE PRSDBM.PRS_PRODCONTRACT_ADDLCHARGE ADD CONSTRAINT PRS_PPA_FK_SP FOREIGN KEY ( SUPP_N ) REFERENCES PRSDBM.PRS_PRDCONTRACT_SUPPLIER ( SUPP_N) ;


  /* ----------------------------------------------------------------------
TABLE: PRS_CTRCT_SUPPLIERPRDC => PRS_PRDCONTRACT_PRODUCT
---------------------------------------------------------------------- */
  CREATE TABLE PRSDBM.PRS_PRDCONTRACT_PRODUCT
  (
    SUPP_PRDC_N   VARCHAR2 (11) NOT NULL ,
    SUPP_N        VARCHAR2 (11) NOT NULL ,
    PRDC_CAT_C    VARCHAR2 (50) NOT NULL ,
    PRDC_REF_N    VARCHAR2 (20) ,
    SUPP_PART_N   VARCHAR2 (20) ,
    MSRUNIT_C    VARCHAR2 (3) ,
    PRDC_QTY_Q 	  NUMBER
  ) ;

COMMENT ON TABLE PRSDBM.PRS_PRDCONTRACT_PRODUCT IS 'This table maintains the supplier product details of the period contract' ;
COMMENT ON COLUMN PRSDBM.PRS_PRDCONTRACT_PRODUCT.SUPP_PRDC_N IS 'Auto generated seq no' ;
COMMENT ON COLUMN PRSDBM.PRS_PRDCONTRACT_PRODUCT.SUPP_N IS 'Contract_Supplier seq no (Reference to PRS_PRDCONTRACT_SUPPLIER)' ;
COMMENT ON COLUMN PRSDBM.PRS_PRDCONTRACT_PRODUCT.PRDC_CAT_C IS 'Product Category Code (Reference to PRSCTABLE)' ;
COMMENT ON COLUMN PRSDBM.PRS_PRDCONTRACT_PRODUCT.PRDC_REF_N IS 'Product Reference No' ;
COMMENT ON COLUMN PRSDBM.PRS_PRDCONTRACT_PRODUCT.SUPP_PART_N IS 'Unique Supplier Part No' ;
COMMENT ON COLUMN PRSDBM.PRS_PRDCONTRACT_PRODUCT.MSRUNIT_C IS 'Code to indicate unit of measurement for each item eg EA (Each)/Box ' ;
COMMENT ON COLUMN PRSDBM.PRS_PRDCONTRACT_PRODUCT.PRDC_QTY_Q IS 'Quantity per unit' ;

 
ALTER TABLE PRSDBM.PRS_PRDCONTRACT_PRODUCT ADD CONSTRAINT PRS_PPP_PK_PN PRIMARY KEY ( SUPP_PRDC_N ) ;
ALTER TABLE PRSDBM.PRS_PRDCONTRACT_PRODUCT ADD CONSTRAINT PRS_PPP_FK_CT FOREIGN KEY ( PRDC_CAT_C ) REFERENCES PRSDBM.PRSCTABLE ( CODE_C ) ;
ALTER TABLE PRSDBM.PRS_PRDCONTRACT_PRODUCT ADD CONSTRAINT PRS_PPP_FK_SP FOREIGN KEY ( SUPP_N ) REFERENCES PRSDBM.PRS_PRDCONTRACT_SUPPLIER ( SUPP_N ) ;
ALTER TABLE PRSDBM.PRS_PRDCONTRACT_PRODUCT ADD CONSTRAINT PRS_PPP_FK_MU FOREIGN KEY ( MSRUNIT_C ) REFERENCES IISDBM.MSRUNIT ( MSRUNIT_C ) ;

  /* ----------------------------------------------------------------------
TABLE: PRS_CTRCT_SUPPLIERPRDCPRCTIER => PRS_PRDCONTRACT_PRODUCTCONTROL
---------------------------------------------------------------------- */
CREATE TABLE PRSDBM.PRS_PRDCONTRACT_PRODUCTCONTROL
  (
    PRDC_CTRL_N  	VARCHAR2 (11) NOT NULL ,
    SUPP_PRDC_N 	VARCHAR2 (11) NOT NULL ,
    QTY_MIN_Q   	NUMBER (3) ,
    QTY_MAX_Q   	NUMBER (3) ,
    UNITPX_A    	NUMBER (10,2)
  ) ;

COMMENT ON TABLE PRSDBM.PRS_PRDCONTRACT_PRODUCT IS 'This control table maintains the supplier product tier details of the period contract' ;
COMMENT ON COLUMN PRSDBM.PRS_PRDCONTRACT_PRODUCTCONTROL.PRDC_CTRL_N IS 'Auto generated seq no' ;
COMMENT ON COLUMN PRSDBM.PRS_PRDCONTRACT_PRODUCTCONTROL.SUPP_PRDC_N IS 'Supplier product  no(Reference to PRS_PRDCONTRACT_PRODUCT)' ;
COMMENT ON COLUMN PRSDBM.PRS_PRDCONTRACT_PRODUCTCONTROL.QTY_MIN_Q IS 'Minimum qty of the tier (order)' ;
COMMENT ON COLUMN PRSDBM.PRS_PRDCONTRACT_PRODUCTCONTROL.QTY_MAX_Q IS 'Maximum qty of the tier (order)' ;
COMMENT ON COLUMN PRSDBM.PRS_PRDCONTRACT_PRODUCTCONTROL.UNITPX_A IS 'Unit price of the product' ;

  ALTER TABLE PRSDBM.PRS_PRDCONTRACT_PRODUCTCONTROL ADD CONSTRAINT PRS_PCT_PK_CN PRIMARY KEY ( PRDC_CTRL_N ) ;
  ALTER TABLE PRSDBM.PRS_PRDCONTRACT_PRODUCTCONTROL ADD CONSTRAINT PRS_PCT_FK_SN FOREIGN KEY ( SUPP_PRDC_N ) REFERENCES PRSDBM.PRS_PRDCONTRACT_PRODUCT ( SUPP_PRDC_N ) ;

 /* ----------------------------------------------------------------------
SEQUENCE
---------------------------------------------------------------------- */

CREATE SEQUENCE PRSDBM.PRS_CONTRACT_PRD_SEQ START WITH 1 MINVALUE 1 NOCACHE ORDER ;
CREATE SEQUENCE PRSDBM.PRS_PRDCONTRACT_PRODUCT_SEQ START WITH 1 MINVALUE 1 NOCACHE ORDER ;
CREATE SEQUENCE PRSDBM.PRS_PRDCONTRACT_PRDCTRL_SEQ START WITH 1 MINVALUE 1 NOCACHE ORDER ;
CREATE SEQUENCE PRSDBM.PRS_PRDCONTRACT_SUPPLIER_SEQ START WITH 1 MINVALUE 1 NOCACHE ORDER ;
CREATE SEQUENCE PRSDBM.PRS_PRDCONTRACT_SUPPADDL_SEQ START WITH 1 MINVALUE 1 NOCACHE ORDER ;

  /* ----------------------------------------------------------------------
GRANTS
---------------------------------------------------------------------- */
  GRANT DELETE, INSERT, SELECT, UPDATE ON PRSDBM.PRS_PERIODCONTRACT_PARTICS TO PRJPRS;
  GRANT DELETE, INSERT, SELECT, UPDATE ON PRSDBM.PRS_PRDCONTRACT_SUPPLIER TO PRJPRS;
  GRANT DELETE, INSERT, SELECT, UPDATE ON PRSDBM.PRS_PRODCONTRACT_ADDLCHARGE TO PRJPRS;
  GRANT DELETE, INSERT, SELECT, UPDATE ON PRSDBM.PRS_PRDCONTRACT_PRODUCT TO PRJPRS;
  GRANT DELETE, INSERT, SELECT, UPDATE ON PRSDBM.PRS_PRDCONTRACT_PRODUCTCONTROL TO PRJPRS;
  
  GRANT SELECT ON PRSDBM.PRS_CONTRACT_PRD_SEQ TO PRJPRS;
  GRANT SELECT ON PRSDBM.PRS_PRDCONTRACT_SUPPLIER_SEQ TO PRJPRS;
  GRANT SELECT ON PRSDBM.PRS_PRDCONTRACT_SUPPADDL_SEQ TO PRJPRS;
  GRANT SELECT ON PRSDBM.PRS_PRDCONTRACT_PRODUCT_SEQ TO PRJPRS;
  GRANT SELECT ON PRSDBM.PRS_PRDCONTRACT_PRDCTRL_SEQ TO PRJPRS;


  GRANT SELECT ON PRSDBM.PRS_PERIODCONTRACT_PARTICS TO RPTPRS;
  GRANT SELECT ON PRSDBM.PRS_PRDCONTRACT_SUPPLIER TO RPTPRS;
  GRANT SELECT ON PRSDBM.PRS_PRODCONTRACT_ADDLCHARGE TO RPTPRS;
  GRANT SELECT ON PRSDBM.PRS_PRDCONTRACT_PRODUCT TO RPTPRS;
  GRANT SELECT ON PRSDBM.PRS_PRDCONTRACT_PRODUCTCONTROL TO RPTPRS;
  
  
  GRANT SELECT ON PRSDBM.PRS_CONTRACT_PRD_SEQ TO RPTPRS;
  GRANT SELECT ON PRSDBM.PRS_PRDCONTRACT_SUPPLIER_SEQ TO RPTPRS;
  GRANT SELECT ON PRSDBM.PRS_PRDCONTRACT_SUPPADDL_SEQ TO RPTPRS;
  GRANT SELECT ON PRSDBM.PRS_PRDCONTRACT_PRODUCT_SEQ TO RPTPRS;
  GRANT SELECT ON PRSDBM.PRS_PRDCONTRACT_PRDCTRL_SEQ TO RPTPRS;

  /* ----------------------------------------------------------------------
INDEXES
---------------------------------------------------------------------- */
CREATE INDEX PRS_PPP_I_PT ON PRSDBM.PRS_PRDCONTRACT_PRODUCT
    ( SUPP_PART_N ASC    ) ;

CREATE UNIQUE INDEX PRS_PCP_UK_CN ON PRSDBM.PRS_PERIODCONTRACT_PARTICS
  (    CON_N ASC  );