  /* ----------------------------------------------------------------------
SYNONYMS
---------------------------------------------------------------------- */
CREATE PUBLIC SYNONYM PRS_PERIODCONTRACT_PARTICS FOR PRSDBM.PRS_PERIODCONTRACT_PARTICS;
CREATE PUBLIC SYNONYM PRS_PRDCONTRACT_SUPPLIER FOR PRSDBM.PRS_PRDCONTRACT_SUPPLIER;
CREATE PUBLIC SYNONYM PRS_PRODCONTRACT_ADDLCHARGE FOR PRSDBM.PRS_PRODCONTRACT_ADDLCHARGE;
CREATE PUBLIC SYNONYM PRS_PRDCONTRACT_PRODUCT FOR PRSDBM.PRS_PRDCONTRACT_PRODUCT;
CREATE PUBLIC SYNONYM PRS_PRDCONTRACT_PRODUCTCONTROL FOR PRSDBM.PRS_PRDCONTRACT_PRODUCTCONTROL;

CREATE PUBLIC SYNONYM PRS_CONTRACT_PRD_SEQ FOR PRSDBM.PRS_CONTRACT_PRD_SEQ;
CREATE PUBLIC SYNONYM PRS_PRDCONTRACT_SUPPLIER_SEQ FOR PRSDBM.PRS_PRDCONTRACT_SUPPLIER_SEQ;
CREATE PUBLIC SYNONYM PRS_PRDCONTRACT_SUPPADDL_SEQ FOR PRSDBM.PRS_PRDCONTRACT_SUPPLIERADDL_SEQ;
CREATE PUBLIC SYNONYM PRS_PRDCONTRACT_PRODUCT_SEQ FOR PRSDBM.PRS_PRDCONTRACT_PRODUCT_SEQ;
CREATE PUBLIC SYNONYM PRS_PRDCONTRACT_PRDCTRL_SEQ FOR PRSDBM.PRS_PRDCONTRACT_PRODUCTPRCT_SEQ;

	