/* NUS Restricted */

-- PRS_INBOUND_STG
CREATE OR REPLACE SYNONYM PRS_INBOUND_STG FOR PRSDBM.PRS_INBOUND_STG;

-- PRS_INBOUND_STG_SEQ
CREATE OR REPLACE SYNONYM PRS_INBOUND_STG_SEQ FOR PRSDBM.PRS_INBOUND_STG_SEQ;