/* NUS Restricted */

/* ----------------------------------------------------------------------
TABLE: PRS_INBOUND_STG
---------------------------------------------------------------------- */
CREATE TABLE PRSDBM.PRS_INBOUND_STG
(
    INBOUND_N VARCHAR2(11) NOT NULL,
    INBOUND_TP_C VARCHAR2(50) NOT NULL,
    INBOUND_PAYLOAD_T CLOB,
    REC_CREATE_DTM DATE NOT NULL,
    INBOUND_PROCSTS_C VARCHAR2(50) NOT NULL
)
;

COMMENT ON TABLE PRSDBM.PRS_INBOUND_STG IS 'This table stores inbound request payload to be processed by PRS batch jobs to update PRS database tables such as SUPPLIER or WBS.';
COMMENT ON COLUMN PRSDBM.PRS_INBOUND_STG.INBOUND_N IS 'Primary key of record. Generated by Oracle sequence.';
COMMENT ON COLUMN PRSDBM.PRS_INBOUND_STG.INBOUND_PAYLOAD_T IS 'Inbound request payload, to be proccessed by PRS batch jobs.';
COMMENT ON COLUMN PRSDBM.PRS_INBOUND_STG.INBOUND_TP_C IS 'Inbound type code. Code to uniquely identify an inbound request type such as supplier or wbs. The code shall be defined in the code table before it can be used.';
COMMENT ON COLUMN PRSDBM.PRS_INBOUND_STG.REC_CREATE_DTM IS 'Record created date. Records will be selected for processing base on this date, inbound request type and  inbound proccess status.';
COMMENT ON COLUMN PRSDBM.PRS_INBOUND_STG.INBOUND_PROCSTS_C IS 'Inbound process status. To mark if record is proccessed by PRS batch jobs. The code shall be defined in the code table before it can be used. E.g INBOUND_STS_NEW or INBOUND_STS_PROCCESSED ';


/* ----------------------------------------------------------------------
CONSTRAINT:  Format is SYSTEM_TABLE_KEY_COL(S)
KEY Type: PK (Primary Key), FK (Foreign Key), UK (Unique Key), CK (Constraint), I (INDEX)
---------------------------------------------------------------------- */

ALTER TABLE PRSDBM.PRS_INBOUND_STG ADD (
CONSTRAINT PRS_PIS_PK_IN
PRIMARY KEY (INBOUND_N)
);

ALTER TABLE PRSDBM.PRS_INBOUND_STG ADD (
CONSTRAINT PRS_PIS_FK_ITC 
FOREIGN KEY ( INBOUND_TP_C )
REFERENCES PRSCTABLE ( CODE_C )
);

ALTER TABLE PRSDBM.PRS_INBOUND_STG ADD (
CONSTRAINT PRS_PIS_FK_IPSC 
FOREIGN KEY ( INBOUND_PROCSTS_C )
REFERENCES PRSCTABLE ( CODE_C )
);


/* ----------------------------------------------------------------------
GRANT: Who and what privilege to grant
---------------------------------------------------------------------- */
GRANT DELETE, INSERT, SELECT, UPDATE ON PRSDBM.PRS_INBOUND_STG TO PRJPRS;
GRANT SELECT ON PRSDBM.PRS_INBOUND_STG TO RPTPRS;

/*
 * Sequences
 */
CREATE SEQUENCE PRSDBM.PRS_INBOUND_STG_SEQ;
GRANT SELECT ON PRSDBM.PRS_INBOUND_STG_SEQ TO PRJPRS;
GRANT SELECT ON PRSDBM.PRS_INBOUND_STG_SEQ TO RPTPRS;