/* NUS Restricted */

-- PRS_API_CONFIG
CREATE OR REPLACE SYNONYM PRS_DELEGATION FOR PRSDBM.PRS_DELEGATION;

-- PRS_API_CONFIG_SEQ
CREATE OR REPLACE SYNONYM PRS_DELEGATION_SEQ FOR PRSDBM.PRS_DELEGATION_SEQ;