-- Purpose : PRS DELEGATION TABLES
--     Date:        2019-04-13 

DROP TABLE PRSDBM.PRS_DELEGATION CASCADE CONSTRAINTS;
CREATE TABLE PRS_DELEGATION (
    DELEGATE_N         VARCHAR2(11) NOT NULL,
    DELEGATE_USER_I    VARCHAR2(12) NOT NULL,
    DELEGATOR_USER_I   VARCHAR2(12) NOT NULL,
    DELEGATE_ROLE_C    VARCHAR2(50) NOT NULL,
    START_DTM          DATE NOT NULL,
    END_DTM            DATE NOT NULL,
    FAC_C              VARCHAR2(2) NOT NULL,
    DEPT_C             VARCHAR2(3) NOT NULL,
	DEFUNCT_F          VARCHAR2(1) DEFAULT 'N' NOT NULL,
    REC_UPDUSER_I      VARCHAR2(12) NOT NULL,
    REC_UPD_DTM        DATE NOT NULL
);

COMMENT ON COLUMN PRS_DELEGATION.DELEGATE_USER_I IS 'Id of the person authorized to represent others';
COMMENT ON COLUMN PRS_DELEGATION.DELEGATOR_USER_I IS 'Id of the person who delegates to others';
COMMENT ON COLUMN PRS_DELEGATION.DELEGATE_ROLE_C IS 'The role that the delegate is going to take for the delegator.';
COMMENT ON COLUMN PRS_DELEGATION.START_DTM IS 'Start of the delegation validity';
COMMENT ON COLUMN PRS_DELEGATION.END_DTM IS 'End of the delegation validity';

ALTER TABLE PRS_DELEGATION ADD CONSTRAINT PRS_DELEGATION_PK PRIMARY KEY ( DELEGATE_N );
ALTER TABLE PRS_DELEGATION ADD CONSTRAINT PRS_DELEGATION_DEPARTMENT_FK FOREIGN KEY ( DEPT_C )
    REFERENCES DEPARTMENT ( DEPT_C );
ALTER TABLE PRS_DELEGATION ADD CONSTRAINT PRS_DELEGATION_FACULTY_FK FOREIGN KEY ( FAC_C )
    REFERENCES FACULTY ( FAC_C );
ALTER TABLE PRS_DELEGATION ADD CONSTRAINT PRS_DELEGATION_PRSCTABLE_FK FOREIGN KEY ( DELEGATE_ROLE_C )
    REFERENCES PRSCTABLE ( CODE_C );
	

GRANT DELETE, INSERT, SELECT, UPDATE ON PRSDBM.PRS_DELEGATION TO PRJPRS;
CREATE SEQUENCE PRSDBM.PRS_DELEGATION_SEQ START WITH 1 INCREMENT BY 1 MINVALUE 1;
GRANT SELECT ON PRSDBM.PRS_DELEGATION_SEQ TO PRJPRS;