/* NUS Restricted */

/* ----------------------------------------------------------------------
TABLE: PRS_CONTROL_PARAM
---------------------------------------------------------------------- */
CREATE TABLE PRSDBM.PRS_CONTROL_PARAM
(
	PARAM_N VARCHAR2(11) NOT NULL,
    PARAM_NM VARCHAR2(50) NOT NULL,
    PARAM_VAL_T VARCHAR2(50) NOT NULL,
    PARAM_DESC_T VARCHAR2(100),
    START_DTM DATE,
    END_DTM DATE
)
;

COMMENT ON TABLE PRSDBM.PRS_CONTROL_PARAM IS 'This table stores generic configuration parameters.';
COMMENT ON COLUMN PRSDBM.PRS_CONTROL_PARAM.PARAM_N IS 'Primary key of record. Generated by Oracle sequence.';
COMMENT ON COLUMN PRSDBM.PRS_CONTROL_PARAM.PARAM_NM IS 'Name of the parameter.';
COMMENT ON COLUMN PRSDBM.PRS_CONTROL_PARAM.PARAM_VAL_T IS 'Value of the parameter.';
COMMENT ON COLUMN PRSDBM.PRS_CONTROL_PARAM.PARAM_DESC_T IS 'Description of the parameter.';
COMMENT ON COLUMN PRSDBM.PRS_CONTROL_PARAM.START_DTM IS 'Effective start date of the parameter.';
COMMENT ON COLUMN PRSDBM.PRS_CONTROL_PARAM.END_DTM IS 'Effective end date of the parameter.';


/* ----------------------------------------------------------------------
CONSTRAINT:  Format is SYSTEM_TABLE_KEY_COL(S)
KEY Type: PK (Primary Key), FK (Foreign Key), UK (Unique Key), CK (Constraint), I (INDEX)
---------------------------------------------------------------------- */

ALTER TABLE PRSDBM.PRS_CONTROL_PARAM ADD (
CONSTRAINT PRS_PCP_PK_PN
PRIMARY KEY (PARAM_N)
);

/* ----------------------------------------------------------------------
GRANT: Who and what privilege to grant
---------------------------------------------------------------------- */
GRANT DELETE, INSERT, SELECT, UPDATE ON PRSDBM.PRS_CONTROL_PARAM TO PRJPRS;
GRANT SELECT ON PRSDBM.PRS_CONTROL_PARAM TO RPTPRS;

/*
 * Sequences
 */
CREATE SEQUENCE PRSDBM.PRS_CONTROL_PARAM_SEQ;
GRANT SELECT ON PRSDBM.PRS_CONTROL_PARAM_SEQ TO PRJPRS;
GRANT SELECT ON PRSDBM.PRS_CONTROL_PARAM_SEQ TO RPTPRS;