/* NUS Restricted */

-- PRS_CONTROL_PARAM
CREATE OR REPLACE SYNONYM PRS_CONTROL_PARAM FOR PRSDBM.PRS_CONTROL_PARAM;


-- PRS_CONTROL_PARAM_SEQ
CREATE OR REPLACE SYNONYM PRS_CONTROL_PARAM_SEQ FOR PRSDBM.PRS_CONTROL_PARAM_SEQ;